services:
  db:
    image: postgres
    container_name: labmon_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: labap_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
    networks:
      - labap_network

  auth_api:
    build: ./auth_api
    container_name: labmon_auth_api
    image: auth_api:latest
    restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/labap_db
      SECRET_KEY: 1234
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - labap_network

  labmon_app:
    build: ./labmon_app
    container_name: labmon_app
    ports:
      - "8080:80"
    depends_on:
      - auth_api

networks:
  labap_network:
    driver: bridge

volumes:
  pgdata: