services:
  db:
    image: postgres
    container_name: labmon_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: labap_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
    networks:
      - labap_network

  auth_api:
    build: ./auth_api
    container_name: labmon_auth_api
    image: auth_api:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/labap_db
      SECRET_KEY: 1234
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - labap_network

  monsters_api:
    build: ./monsters_api
    container_name: labmon_monsters_api
    image: monsters_api:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/labap_db
      SECRET_KEY: 1234
    ports:
      - "5002:5000"
    depends_on:
      - db
    networks:
      - labap_network

  items_api:
    build: ./items_api
    container_name: labmon_items_api
    image: items_api:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/labap_db
      SECRET_KEY: 1234
    ports:
      - "5003:5000"
    depends_on:
      - db
    networks:
      - labap_network

  labmon_app:
    build: ./labmon_app
    container_name: labmon_app
    restart: unless-stopped
    ports:
      - "5005:80"
    depends_on:
      - auth_api
    networks:
      - labap_network

networks:
  labap_network:
    driver: bridge

volumes:
  pgdata: