services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    depends_on:
      - db
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - labap_network

  db:
    image: postgres
    container_name: labmon_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: labap_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
    networks:
      - labap_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: labmon_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin:Z
    networks:
      - labap_network


  auth_api:
    build: ./auth_api
    container_name: labmon_auth_api
    image: auth_api:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/labap_db
      SECRET_KEY: 1234
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
    ports:
      - "5001:5000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - labap_network

  monsters_api:
    build: ./monsters_api
    container_name: labmon_monsters_api
    image: monsters_api:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/labap_db
      SECRET_KEY: 1234
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5002:5000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - labap_network

  items_api:
    build: ./items_api
    container_name: labmon_items_api
    image: items_api:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/labap_db
      SECRET_KEY: 1234
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5003:5000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - labap_network
  
  game_api:
    build: ./game_api
    container_name: labmon_game_api
    image: game_api:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/labap_db
      SECRET_KEY: 1234
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5004:5000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - labap_network

  labmon_app:
    build: ./labmon_app
    container_name: labmon_app
    restart: unless-stopped
    ports:
      - "5005:80"
    depends_on:
      - auth_api
    networks:
      - labap_network

networks:
  labap_network:
    driver: bridge

volumes:
  pgdata:
  pgadmin_data: